# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Item JAN code')),
                ('name', models.CharField(max_length=255, verbose_name='Item name')),
                ('cost_price', models.IntegerField(verbose_name='Cost price')),
                ('selling_price', models.IntegerField(verbose_name='Selling price')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settion_id', models.IntegerField(verbose_name='Settion Id')),
                ('value', models.IntegerField(verbose_name='value')),
                ('date', models.DateTimeField(verbose_name='sold date')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='cms.Item', verbose_name='Item JAN code')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=0, verbose_name='Student ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='sales',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='cms.User', verbose_name='User ID'),
        ),
    ]
