# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='item',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='user',
        ),
        migrations.AddField(
            model_name='sales',
            name='item_code',
            field=models.IntegerField(default=0, verbose_name='Item JAN code'),
        ),
        migrations.AddField(
            model_name='sales',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='Student ID'),
        ),
    ]
