# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20160420_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='price',
            field=models.IntegerField(default=0, verbose_name='price'),
        ),
    ]
