# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.IntegerField(default=0, verbose_name='Item JAN code'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost_price',
            field=models.IntegerField(default=0, verbose_name='Cost price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='selling_price',
            field=models.IntegerField(default=0, verbose_name='Selling price'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='settion_id',
            field=models.IntegerField(default=0, verbose_name='Settion Id'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='value',
            field=models.IntegerField(default=0, verbose_name='value'),
        ),
    ]
