# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20160420_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='user_id',
        ),
        migrations.AddField(
            model_name='sale',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cms.Item'),
        ),
        migrations.AddField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cms.User'),
        ),
    ]
