# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20160421_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='settion_id',
        ),
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
    ]
