# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-22 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20160511_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.IntegerField(default=0, unique=True, verbose_name='Student ID'),
        ),
    ]
